from pydantic import BaseModel, Field
from typing import List, Optional

class MemoryItem(BaseModel):
    """
    Represents an individual unit of persistent memory context.
    """
    type: str = Field(..., description="The category of memory (e.g., 'architecture', 'preference', 'bug_fix')")
    content: str = Field(..., description="The actual text content of the memory")

class ChatRequest(BaseModel):
    """
    Schema for incoming chat messages.
    """
    message: str = Field(..., description="The user's query or instruction for the AI engineer")

class ChatResponse(BaseModel):
    """
    Schema for the chat response, including generated reply and memory context utilized.
    """
    reply: str = Field(..., description="The text response generated by MemoryForge AI Engineer")
    memory_context: List[MemoryItem] = Field(
        default_factory=list,
        description="The relevant memory items used to contextualize the agent's response"
    )

class MemoriesResponse(BaseModel):
    """
    Schema for memories retrieval endpoint.
    """
    count: int = Field(..., description="The total number of memory items retrieved")
    memories: List[MemoryItem] = Field(default_factory=list, description="List of memory items")

class UserRegister(BaseModel):
    name: str = Field(..., min_length=2, max_length=50)
    email: str = Field(..., description="Email address")
    password: str = Field(..., min_length=6)
    role: str = Field(default="USER", description="Role of the user (USER or ADMIN)")

class UserLogin(BaseModel):
    email: str
    password: str

class UserResponse(BaseModel):
    id: str
    name: str
    email: str
    role: str

class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    user: UserResponse

class KnowledgeItem(BaseModel):
    id: Optional[str] = Field(None, description="The string ID of the knowledge record")
    title: str = Field(..., description="Title of the knowledge document")
    content: str = Field(..., description="Detailed text content")

class KnowledgeResponse(BaseModel):
    count: int = Field(..., description="Total count of knowledge entries")
    knowledge: List[KnowledgeItem] = Field(default_factory=list, description="List of knowledge base entries")

