from pydantic import BaseModel, Field
from typing import List

class MemoryItem(BaseModel):
    """
    Represents an individual unit of persistent memory context.
    """
    type: str = Field(..., description="The category of memory (e.g., 'architecture', 'preference', 'bug_fix')")
    content: str = Field(..., description="The actual text content of the memory")

class ChatRequest(BaseModel):
    """
    Schema for incoming chat messages.
    """
    message: str = Field(..., description="The user's query or instruction for the AI engineer")

class ChatResponse(BaseModel):
    """
    Schema for the chat response, including generated reply and memory context utilized.
    """
    reply: str = Field(..., description="The text response generated by MemoryForge AI Engineer")
    memory_context: List[MemoryItem] = Field(
        default_factory=list,
        description="The relevant memory items used to contextualize the agent's response"
    )

class MemoriesResponse(BaseModel):
    """
    Schema for memories retrieval endpoint.
    """
    count: int = Field(..., description="The total number of memory items retrieved")
    memories: List[MemoryItem] = Field(default_factory=list, description="List of memory items")
